### ISSUE TITLE
dvsdvsdvsdva.com

### ISSUE THREAD

**Issue by FadeMind** [manic-code/Emerging-Malicious-Domain-Blocklist#1]
Domain to whitelist: `dvsdvsdvsdva.com`

Issue

filemoon.sx use this domain for stream delivery

Already reported issue to quad9 and OISD maintainer. 
Also @hagezi ignored issue cause "others block this domain too, so I will not fix that". 
https://github.com/hagezi/dns-blocklists/issues/615

**Comment by hagezi** [comment]
I didn't ignore it, but rejected it because the domains are flagged and blocked by Qua9. If anyone can do SecureDNS, it is Quad9. If these domains do not represent a security risk, then "the operator" should request deletion from Quad9 and ensure that the flags are removed.

**Comment by manic-code** [comment]
I've taken a deeper look into the domain and its associated IPs and all appears normal. It will be removed from the blocklist, please allow up to a day for the changes to be reflected on Hagezi's list.

**Comment by manic-code** [comment]
> I didn't ignore it, but rejected it because the domains are flagged and blocked by Qua9. If anyone can do SecureDNS, it is Quad9. If these domains do not represent a security risk, then "the operator" should request deletion from Quad9 and ensure that the flags are removed.

Oops, I missed this reply. I second Hagezi's comment, should absolutely report this to Quad9, they have always replied quickly to my whitelist suggestions. https://quad9.net/support/contact

**Comment by FadeMind** [comment]
@manic-code I already sent e-mail to quad9.

**Comment by hagezi** [comment]
This is the source of why it is on the Quad9 block list:

https://exchange.xforce.ibmcloud.com/url/dvsdvsdvsdva.com

**Comment by FadeMind** [comment]
@manic-code @hagezi  
![20230311-1678548123](https://user-images.githubusercontent.com/9846948/224492737-a1b68cb4-956d-472a-9b6a-69c1c1190444.png)

**Comment by hagezi** [comment]
Thanks @FadeMind removed from my lists.

**Comment by FadeMind** [comment]
@hagezi Thank you. I understand and respect the security rules of domain removal. I'm glad I was able to help. 
ping @sjhgvr

**Comment by hagezi** [comment]
The problem is, you don't always find out why something is flagged. I then rely on competent SecureDNS like Quad9.
